In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('./data/heart_disease_health_indicators_BRFSS2015.csv').dropna()
with pd.option_context('display.max_columns', None):
    display(df)

,HeartDiseaseorAttack,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,Diabetes,PhysActivity,Fruits,Veggies,HvyAlcoholConsump,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,0.0,1.0,1.0,1.0,18.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,1.0,1.0,1.0,1.0,25.0,0.0,0.0,2.0,1.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [3]:
categorical = [
    'Diabetes',
]

numeric = {
    'BMI': [-0.01, 20, 30, 40, np.inf],
    'PhysHlth': [-0.01, 0, 10, np.inf],
    'MentHlth': [-0.01, 0, 10, np.inf],
    'Age': [-0.01, 5, 10, np.inf],
    'Income': [-0.01, 3, 6, 7, np.inf],
    'Education': [-0.01, 3, 5, np.inf],
}

scores = [
    'GenHlth',
]

In [4]:


df = df[categorical + list(numeric.keys()) + scores + ['HeartDiseaseorAttack']]

for col in categorical:
    print(col)
    binarized = pd.get_dummies(df[col], prefix=col)
    df = df.join(binarized).drop(columns=[col])

df = df.astype(float)
with pd.option_context('display.max_columns', None):
    display(df)

Diabetes

,BMI,PhysHlth,MentHlth,Age,Income,Education,GenHlth,HeartDiseaseorAttack,Diabetes_0.0,Diabetes_1.0,Diabetes_2.0
0,40.0,15.0,18.0,9.0,3.0,4.0,5.0,0.0,1.0,0.0,0.0
1,25.0,0.0,0.0,7.0,1.0,6.0,3.0,0.0,1.0,0.0,0.0
2,28.0,30.0,30.0,9.0,8.0,4.0,5.0,0.0,1.0,0.0,0.0
3,27.0,0.0,0.0,11.0,6.0,3.0,2.0,0.0,1.0,0.0,0.0
4,24.0,0.0,3.0,11.0,4.0,5.0,2.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
253675,45.0,5.0,0.0,5.0,7.0,6.0,3.0,0.0,1.0,0.0,0.0
253676,18.0,0.0,0.0,11.0,4.0,2.0,4.0,0.0,0.0,0.0,1.0
253677,28.0,0.0,0.0,2.0,2.0,5.0,1.0,0.0,1.0,0.0,0.0
253678,23.0,0.0,0.0,7.0,1.0,5.0,3.0,0.0,1.0,0.0,0.0
253679,25.0,0.0,0.0,9.0,2.0,6.0,2.0,1.0,0.0,0.0,1.0

In [5]:
heart_X = df.drop(columns=['HeartDiseaseorAttack'])
heart_y = df['HeartDiseaseorAttack']
heart_X_train, heart_X_test, heart_y_train, heart_y_test = train_test_split(
    heart_X,
    heart_y,
    train_size=700,
    test_size=300,
    random_state=0,
    stratify=heart_y
)
heart_X_train.to_csv('heart_X_train.csv', index=False)
heart_X_test.to_csv('heart_X_test.csv', index=False)
heart_y_train.to_csv('heart_y_train.csv', index=False)
heart_y_test.to_csv('heart_y_test.csv', index=False)

In [6]:
df_bin = df.copy()

for col in scores:
    print(col)
    binarized = (df[[col]] >= 4).rename(columns={col: f'{col}_ge_4'})
    df_bin = df_bin.join(binarized).drop(columns=[col])

for col, bins in numeric.items():
    print(col)
    binarized = pd.get_dummies(pd.cut(df[col], bins=bins), prefix=f'{col}')
    df_bin = df_bin.join(binarized).drop(columns=[col])

df_bin = df_bin.astype(int, errors='raise')

with pd.option_context('display.max_columns', None):
    display(df_bin)

GenHlth
BMI

PhysHlth
MentHlth
Age
Income
Education

,HeartDiseaseorAttack,Diabetes_0.0,Diabetes_1.0,Diabetes_2.0,GenHlth_ge_4,"BMI_(-0.01, 20.0]","BMI_(20.0, 30.0]","BMI_(30.0, 40.0]","BMI_(40.0, inf]","PhysHlth_(-0.01, 0.0]","PhysHlth_(0.0, 10.0]","PhysHlth_(10.0, inf]","MentHlth_(-0.01, 0.0]","MentHlth_(0.0, 10.0]","MentHlth_(10.0, inf]","Age_(-0.01, 5.0]","Age_(5.0, 10.0]","Age_(10.0, inf]","Income_(-0.01, 3.0]","Income_(3.0, 6.0]","Income_(6.0, 7.0]","Income_(7.0, inf]","Education_(-0.01, 3.0]","Education_(3.0, 5.0]","Education_(5.0, inf]"
0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,1,0,1,0,0,0,0,1,0
1,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1
2,0,1,0,0,1,0,1,0,0,0,0,1,0,0,1,0,1,0,0,0,0,1,0,1,0
3,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0
4,0,1,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0,1,0,0,0,0,0,0,1,0,1,0,1,0,0,1,0,0,0,0,1,0,0,0,1
253676,0,0,0,1,1,1,0,0,0,1,0,0,1,0,0,0,0,1,0,1,0,0,1,0,0
253677,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0
253678,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,1,0
253679,1,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,1

In [7]:
heart_bin_X = df_bin.drop(columns=['HeartDiseaseorAttack'])
heart_bin_y = df_bin['HeartDiseaseorAttack']
heart_bin_X_train, heart_bin_X_test, heart_bin_y_train, heart_bin_y_test = train_test_split(
    heart_bin_X,
    heart_bin_y,
    train_size=700,
    test_size=300,
    random_state=0,
    stratify=heart_bin_y
)
heart_bin_X_train.to_csv('heart_bin_X_train.csv', index=False)
heart_bin_X_test.to_csv('heart_bin_X_test.csv', index=False)
heart_bin_y_train.to_csv('heart_bin_y_train.csv', index=False)
heart_bin_y_test.to_csv('heart_bin_y_test.csv', index=False)